### ISSUE TITLE
Compat bounds in the registry

### ISSUE THREAD

**Issue by albheim** [Pat-Laub/EMpht.jl#2]
For packages that do not implement compat bounds themselves the general registry has added some at some point in time
https://github.com/JuliaRegistries/General/blob/master/E/EMpht/Compat.toml

This seems more restrictive than necessary, specifically keeping Distributions to an older version which prevents current version of many other packages I wanted to use together. I have tried to dev this and tested it with newer Distributions than that defined in the registry compat, and all seems to work fine.

If you add compat bounds and tag a new version it should replace the compat bounds in the registry. I could put together a PR with some relaxed bounds if you want, and just check that the tests pass.

**Comment by Pat-Laub** [comment]
Thanks very much Albin for letting me know what was the cause of this problem. I had noticed on new installs that EMpht installs caused some dependencies to be downgraded, but didn't know enough about the cause to fix it. If you `] update EMpht` to the new version 0.1.1, does this solve this problem for you? Tusen tack!

**Comment by albheim** [comment]
Seems to install fine at least, will report if anything seems off.

Haha, tack själv!
